### ISSUE TITLE
pygrun is wrong

### ISSUE THREAD

**Issue by Grit-he** [jszheng/py3antlr4book#14]
when i run pygrun Hello r --tokens input.txt
Traceback (most recent call last):
  File "/home/hehongbin/桌面/py3antlr4book-master/bin/pygrun", line 178, in <module>
    module_lexer = __import__(lexerName, globals(), locals(), lexerName)
  File "/home/hehongbin/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/hehongbin/桌面/py3antlr4book-master/01-Hello/./HelloLexer.py", line 25, in <module>
    class HelloLexer(Lexer):
  File "/home/hehongbin/桌面/py3antlr4book-master/01-Hello/./HelloLexer.py", line 27, in HelloLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/usr/local/lib/python3.8/dist-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/usr/local/lib/python3.8/dist-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
this question arises, how can i solve this question?thanks

**Comment by t0hka1** [comment]
> 
Try to run this command and your problem will be solve!
`pip install antlr4-python3-runtime==4.7.2`
